/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 */

import { ShiftCountPreference, SHIFT_COUNT } from "@/types/scheduling";
import {
  compileContractedHours,
  compileContractedHoursPolicy,
  confirmGenericToContractedHours,
  confirmRefresh,
  ContractedHoursDraft,
  ContractedHoursPreference,
  ContractedHoursResult,
  ContractedHoursScenario,
  convertContractedHoursToGeneric,
  expandContractedHoursShiftTypes,
  getContractedHoursLeaveCreditOutcome,
  hoursToHalfHourUnits,
  previewGenericToContractedHours,
  previewRefresh,
  reconcileContractedHoursDraftSelectors,
  restoreRefreshSnapshot,
  validateContractedHours,
  validateContractedHoursScenario,
} from "@/utils/contractedHours";
import { ALL, LEAVE, OFF } from "@/utils/keywords";

function valueOf<T>(result: ContractedHoursResult<T>): T {
  expect(result.ok).toBe(true);
  if (!result.ok) {
    throw new Error(result.error.message);
  }
  return result.value;
}

function errorOf<T>(result: ContractedHoursResult<T>) {
  expect(result.ok).toBe(false);
  if (result.ok) {
    throw new Error("Expected a contracted-hours domain error.");
  }
  return result.error;
}

const scenario: ContractedHoursScenario = {
  shiftTypes: {
    items: [
      { id: "D", description: "Day", durationMinutes: 480 },
      { id: "E", description: "Evening", durationMinutes: 510 },
      { id: "N", description: "Night" },
    ],
    groups: [
      { id: "Early", description: "", members: ["D", "E"] },
      { id: "Clinical", description: "", members: ["Early", "N", LEAVE] },
      { id: "Empty", description: "", members: [] },
    ],
  },
};

const normalizedScenario: ContractedHoursScenario = {
  shiftTypes: {
    items: [
      { id: "D", description: "Day", durationMinutes: 480 },
      { id: OFF, description: "Off shift type", isAutoGenerated: true },
      { id: LEAVE, description: "Paid leave day-state", isAutoGenerated: true },
    ],
    groups: [
      { id: "Work", description: "", members: [ALL, LEAVE] },
      { id: "NestedWork", description: "", members: ["Work"] },
      {
        id: ALL,
        description: "Group containing all shift types",
        members: ["D"],
        isAutoGenerated: true,
      },
    ],
  },
};

function compileExact(
  countShiftTypes: string[] = ["D"],
  existingCoefficients?: [string, number | ""][],
): ContractedHoursPreference {
  return valueOf(compileContractedHours({
    description: "160h",
    person: ["P1"],
    countDates: [ALL],
    countShiftTypes,
    target: { policy: "exact", totalHours: 160 },
    existingCoefficients,
  }, scenario));
}

describe("contracted-hours compiler", () => {
  it("compiles Exact and Range totals into fixed hard half-hour fields", () => {
    expect(valueOf(compileContractedHoursPolicy({
      policy: "exact",
      totalHours: 160,
    }))).toEqual({
      hoursContract: { unit: "half-hour", policy: "exact" },
      expression: "x = T",
      target: 320,
      weight: Number.POSITIVE_INFINITY,
    });

    expect(valueOf(compileContractedHoursPolicy({
      policy: "range",
      minimumHours: 150,
      maximumHours: 170,
    }))).toEqual({
      hoursContract: { unit: "half-hour", policy: "range" },
      expression: ["x >= T", "x <= T"],
      target: [300, 340],
      weight: Number.POSITIVE_INFINITY,
    });
  });

  it("rejects negative, off-grid, non-finite, and reversed human totals", () => {
    expect(errorOf(hoursToHalfHourUnits(-0.5)).code).toBe("invalid_target");
    expect(errorOf(hoursToHalfHourUnits(8.25)).code).toBe("invalid_target");
    expect(errorOf(hoursToHalfHourUnits(Number.NaN)).code).toBe("invalid_target");
    expect(errorOf(compileContractedHoursPolicy({
      policy: "range",
      minimumHours: 170,
      maximumHours: 150,
    })).code).toBe("invalid_range");
  });

  it("persists selectors, validates in backend semantic order, and displays coefficients in item order", () => {
    const expansion = valueOf(expandContractedHoursShiftTypes(
      scenario.shiftTypes,
      ["Clinical", "D"],
    ));

    expect(expansion.persistedSelectorOrder).toEqual(["Clinical", "D"]);
    expect(expansion.semanticIds).toEqual([LEAVE, "D", "E", "N"]);
    expect(expansion.displayIds).toEqual(["D", "E", "N", LEAVE]);
  });

  it("derives exact worked and LEAVE coefficients without rounding", () => {
    const contract = valueOf(compileContractedHours({
      person: ["P1"],
      countDates: [ALL],
      countShiftTypes: ["Early", LEAVE],
      target: { policy: "range", minimumHours: 150, maximumHours: 170 },
    }, scenario));

    expect(contract.countShiftTypeCoefficients).toEqual([
      ["D", 16],
      ["E", 17],
      [LEAVE, 16],
    ]);
  });

  it("accepts a valid explicit coefficient when working time is absent", () => {
    const contract = compileExact(["N"], [["N", 15]]);
    expect(contract.countShiftTypeCoefficients).toEqual([["N", 15]]);
  });

  it("blocks creation when neither derivation nor an explicit value covers a row", () => {
    const error = errorOf(compileContractedHours({
      person: ["P1"],
      countDates: [ALL],
      countShiftTypes: ["N"],
      target: { policy: "exact", totalHours: 160 },
    }, scenario));
    expect(error).toMatchObject({
      code: "non_derivable_coefficient",
      path: "countShiftTypeCoefficients.N",
    });
  });
});

describe("backend-equivalent expansion and diagnostics", () => {
  it("expands ALL to worked items only and rejects reachable OFF", () => {
    expect(valueOf(expandContractedHoursShiftTypes(
      scenario.shiftTypes,
      [ALL],
    )).semanticIds).toEqual(["D", "E", "N"]);

    const direct = errorOf(expandContractedHoursShiftTypes(
      scenario.shiftTypes,
      [OFF],
    ));
    expect(direct.message).toBe("'OFF' is not allowed in a contracted-hours shift count.");

    const nestedOff = {
      ...scenario.shiftTypes,
      groups: [{ id: "Rest", description: "", members: [OFF] }],
    };
    expect(errorOf(expandContractedHoursShiftTypes(nestedOff, ["Rest"])).code)
      .toBe("off_not_allowed");
  });

  it("reports unresolved, forward, cyclic, and empty graphs deterministically", () => {
    const forwardAndCycle = {
      items: scenario.shiftTypes.items,
      groups: [
        { id: "A", description: "", members: ["B"] },
        { id: "B", description: "", members: ["A"] },
      ],
    };
    expect(errorOf(expandContractedHoursShiftTypes(
      forwardAndCycle,
      ["A"],
    )).message).toBe(
      "Shift type group 'A' references undefined shift type or group ID 'B' (forward reference, cycle, or unknown id).",
    );

    const unknown = {
      items: scenario.shiftTypes.items,
      groups: [{ id: "Broken", description: "", members: ["Missing"] }],
    };
    expect(errorOf(expandContractedHoursShiftTypes(unknown, ["D"])).message).toContain(
      "group 'Broken' references undefined",
    );
    expect(errorOf(expandContractedHoursShiftTypes(
      scenario.shiftTypes,
      ["Missing"],
    )).message).toBe("Unknown shift type ID: Missing");
    expect(errorOf(expandContractedHoursShiftTypes(
      scenario.shiftTypes,
      ["Empty"],
    )).code).toBe("empty_expansion");
    expect(errorOf(expandContractedHoursShiftTypes(
      scenario.shiftTypes,
      [],
    )).code).toBe("empty_selectors");
  });

  it("gives ordered map construction precedence over policy failures", () => {
    const brokenScenario: ContractedHoursScenario = {
      shiftTypes: {
        items: scenario.shiftTypes.items,
        groups: [{ id: "Broken", description: "", members: ["Missing"] }],
      },
    };
    const invalidPolicy = {
      ...compileExact(),
      weight: 1,
    };
    expect(errorOf(validateContractedHours(brokenScenario, invalidPolicy)).code)
      .toBe("group_reference");
  });
});

describe("normalized frontend-state parity", () => {
  it("keeps reserved ALL worked-only inside earlier and nested user groups", () => {
    const work = valueOf(expandContractedHoursShiftTypes(
      normalizedScenario.shiftTypes,
      ["Work"],
    ));
    const nested = valueOf(expandContractedHoursShiftTypes(
      normalizedScenario.shiftTypes,
      ["NestedWork"],
    ));

    expect(work).toEqual({
      persistedSelectorOrder: ["Work"],
      semanticIds: [LEAVE, "D"],
      displayIds: ["D", LEAVE],
    });
    expect(nested.semanticIds).toEqual([LEAVE, "D"]);
    expect(valueOf(expandContractedHoursShiftTypes(
      normalizedScenario.shiftTypes,
      [ALL],
    )).semanticIds).toEqual(["D"]);
  });

  it("ignores the generated ALL representation even if its normalized members are stale", () => {
    const staleGeneratedAll: ContractedHoursScenario = {
      shiftTypes: {
        ...normalizedScenario.shiftTypes,
        groups: normalizedScenario.shiftTypes.groups.map(group =>
          group.id === ALL
            ? { ...group, members: ["D", OFF, LEAVE] }
            : group
        ),
      },
    };

    expect(valueOf(expandContractedHoursShiftTypes(
      staleGeneratedAll.shiftTypes,
      [ALL],
    )).semanticIds).toEqual(["D"]);
  });

  it("keeps compile, Refresh, validation, and LEAVE assistance on the backend expansion", () => {
    const contract = valueOf(compileContractedHours({
      person: ["P1"],
      countDates: [ALL],
      countShiftTypes: ["NestedWork"],
      target: { policy: "exact", totalHours: 160 },
    }, normalizedScenario));

    expect(contract.countShiftTypeCoefficients).toEqual([
      ["D", 16],
      [LEAVE, 16],
    ]);
    expect(valueOf(validateContractedHours(normalizedScenario, contract)))
      .toMatchObject({
        kind: "contracted-hours",
        expansion: {
          semanticIds: [LEAVE, "D"],
          displayIds: ["D", LEAVE],
        },
      });
    expect(valueOf(previewRefresh(
      contract as ContractedHoursDraft,
      normalizedScenario,
    )).replacementDraft.countShiftTypeCoefficients).toEqual([
      ["D", 16],
      [LEAVE, 16],
    ]);
    expect(getContractedHoursLeaveCreditOutcome(normalizedScenario, contract).status)
      .toBe("credited");
  });

  it("still rejects OFF reached through a normalized user group", () => {
    const withOff: ContractedHoursScenario = {
      shiftTypes: {
        ...normalizedScenario.shiftTypes,
        groups: [
          { id: "Bad", description: "", members: [ALL, OFF] },
          ...normalizedScenario.shiftTypes.groups,
        ],
      },
    };
    expect(errorOf(expandContractedHoursShiftTypes(
      withOff.shiftTypes,
      ["Bad"],
    ))).toMatchObject({
      code: "off_not_allowed",
      message: "'OFF' is not allowed in a contracted-hours shift count.",
    });
  });
});

describe("strict marked validation", () => {
  it("accepts Exact and Range and leaves generic arrays byte-identical", () => {
    const exact = compileExact(["D", LEAVE]);
    expect(valueOf(validateContractedHours(scenario, exact)).kind)
      .toBe("contracted-hours");

    const range = valueOf(compileContractedHours({
      person: ["P1"],
      countDates: [ALL],
      countShiftTypes: ["Early"],
      target: { policy: "range", minimumHours: 150, maximumHours: 170 },
    }, scenario));
    expect(valueOf(validateContractedHours(scenario, range)).kind)
      .toBe("contracted-hours");

    const generic: ShiftCountPreference = {
      type: SHIFT_COUNT,
      person: ["P1"],
      countDates: [ALL],
      countShiftTypes: ["D"],
      countShiftTypeCoefficients: [["D", 2]],
      expression: ["x >= T", "x <= T", "x = T"],
      target: [1, 4, 2],
      weight: 3,
    };
    const before = structuredClone(generic);
    const result = valueOf(validateContractedHours(scenario, generic));
    expect(result).toEqual({ kind: "generic", preference: generic });
    expect(generic).toEqual(before);
    expect(result.preference).toBe(generic);
  });

  it("matches policy diagnostic precedence", () => {
    const base = compileExact();
    expect(errorOf(validateContractedHours(scenario, { ...base, weight: 1 })).code)
      .toBe("invalid_weight");
    expect(errorOf(validateContractedHours(scenario, {
      ...base,
      expression: "x >= T",
    })).code).toBe("invalid_expression");
    expect(errorOf(validateContractedHours(scenario, {
      ...base,
      target: [1, 2],
    })).code).toBe("invalid_target");

    const range = valueOf(compileContractedHours({
      person: ["P1"],
      countDates: [ALL],
      countShiftTypes: ["D"],
      target: { policy: "range", minimumHours: 1, maximumHours: 2 },
    }, scenario));
    expect(errorOf(validateContractedHours(scenario, {
      ...range,
      target: [5, 4],
    })).code).toBe("invalid_range");
  });

  it("rejects invalid, non-concrete, duplicate, missing, and extra coefficients in backend order", () => {
    const base = compileExact(["Early"]);
    expect(errorOf(validateContractedHours(scenario, {
      ...base,
      countShiftTypeCoefficients: [["D", 0], ["E", 17]],
    })).code).toBe("invalid_coefficient");
    expect(errorOf(validateContractedHours(scenario, {
      ...base,
      countShiftTypeCoefficients: [["Early", 16]],
    })).code).toBe("non_concrete_coefficient");
    expect(errorOf(validateContractedHours(scenario, {
      ...base,
      countShiftTypeCoefficients: [["D", 16], ["D", 16], ["E", 17]],
    })).code).toBe("duplicate_coefficient");
    expect(errorOf(validateContractedHours(scenario, {
      ...base,
      countShiftTypeCoefficients: [["D", 16]],
    })).code).toBe("missing_coefficient");
    expect(errorOf(validateContractedHours(scenario, {
      ...base,
      countShiftTypeCoefficients: [["D", 16], ["E", 17], ["N", 16]],
    })).code).toBe("extra_coefficient");
  });

  it("validates a scenario in preference order after one ordered-map build", () => {
    const invalidFirst = { ...compileExact(), weight: 2 };
    const invalidSecond = {
      ...compileExact(),
      countShiftTypeCoefficients: [],
    };
    expect(errorOf(validateContractedHoursScenario({
      ...scenario,
      preferences: [invalidFirst, invalidSecond],
    })).code).toBe("invalid_weight");
  });
});

describe("explicit Refresh lifecycle", () => {
  it("previews membership growth, confirms locally, and restores one undo snapshot", () => {
    const stored = compileExact(["Early"]);
    const draft = structuredClone(stored) as ContractedHoursDraft;
    const changedScenario: ContractedHoursScenario = {
      shiftTypes: {
        ...scenario.shiftTypes,
        groups: [
          { id: "Early", description: "", members: ["D", "E", "N"] },
        ],
      },
    };
    const before = structuredClone(draft);
    const preview = valueOf(previewRefresh(draft, changedScenario));

    expect(preview.added).toEqual([{
      id: "N",
      before: "",
      after: "",
      derivable: false,
      blocking: true,
    }]);
    expect(preview.nonDerivable).toEqual(preview.added);
    expect(preview.blocking).toBe(true);
    expect(draft).toEqual(before);

    const transaction = confirmRefresh(preview);
    expect(transaction.draft.countShiftTypeCoefficients).toEqual([
      ["D", 16],
      ["E", 17],
      ["N", ""],
    ]);
    expect(transaction.undoSnapshot).toEqual(before);
    expect(restoreRefreshSnapshot(transaction).draft).toEqual(before);
  });

  it("re-derives changed working time only on confirmed Refresh", () => {
    const stored = compileExact(["D"]);
    const changedScenario: ContractedHoursScenario = {
      shiftTypes: {
        ...scenario.shiftTypes,
        items: scenario.shiftTypes.items.map(item =>
          item.id === "D" ? { ...item, durationMinutes: 510 } : item
        ),
      },
    };

    expect(stored.countShiftTypeCoefficients).toEqual([["D", 16]]);
    const preview = valueOf(previewRefresh(stored as ContractedHoursDraft, changedScenario));
    expect(preview.changed).toEqual([{
      id: "D",
      before: 16,
      after: 17,
      derivable: true,
      blocking: false,
    }]);
    expect(stored.countShiftTypeCoefficients).toEqual([["D", 16]]);
    expect(confirmRefresh(preview).draft.countShiftTypeCoefficients).toEqual([["D", 17]]);
  });

  it("retains non-derivable manual values and reports missing values as blocking", () => {
    const manual = compileExact(["N"], [["N", 15]]) as ContractedHoursDraft;
    const manualPreview = valueOf(previewRefresh(manual, scenario));
    expect(manualPreview.nonDerivable).toEqual([{
      id: "N",
      before: 15,
      after: 15,
      derivable: false,
      blocking: false,
    }]);
    expect(manualPreview.blocking).toBe(false);

    const missing = {
      ...manual,
      countShiftTypeCoefficients: [],
    } as ContractedHoursDraft;
    const missingPreview = valueOf(previewRefresh(missing, scenario));
    expect(missingPreview.nonDerivable[0].blocking).toBe(true);
    expect(missingPreview.replacementDraft.countShiftTypeCoefficients).toEqual([["N", ""]]);
  });

  it("adds LEAVE at 16, removes unreachable rows, and uses the persisted overnight duration", () => {
    const overnightScenario: ContractedHoursScenario = {
      shiftTypes: {
        items: [
          {
            id: "NIGHT",
            description: "Overnight",
            startTime: "20:00",
            endTime: "05:00",
            restMinutes: 30,
            durationMinutes: 510,
          },
        ],
        groups: [],
      },
    };
    const contract = valueOf(compileContractedHours({
      person: ["P1"],
      countDates: [ALL],
      countShiftTypes: ["NIGHT", LEAVE],
      target: { policy: "exact", totalHours: 160 },
    }, overnightScenario));
    expect(contract.countShiftTypeCoefficients).toEqual([
      ["NIGHT", 17],
      [LEAVE, 16],
    ]);

    const draft = {
      ...contract,
      countShiftTypes: [LEAVE],
    } as ContractedHoursDraft;
    const preview = valueOf(previewRefresh(draft, overnightScenario));
    expect(preview.removed.map(row => row.id)).toEqual(["NIGHT"]);
    expect(preview.replacementDraft.countShiftTypeCoefficients).toEqual([[LEAVE, 16]]);
  });

  it("prunes selector removals immediately and adds selector rows blank without deadlocking Refresh", () => {
    const draft = compileExact(["Early"]) as ContractedHoursDraft;
    const removed = valueOf(reconcileContractedHoursDraftSelectors(
      draft,
      ["D"],
      scenario,
    ));
    expect(removed.countShiftTypeCoefficients).toEqual([["D", 16]]);

    const added = valueOf(reconcileContractedHoursDraftSelectors(
      removed,
      ["D", "N"],
      scenario,
    ));
    expect(added.countShiftTypeCoefficients).toEqual([["D", 16], ["N", ""]]);
    const refreshed = valueOf(previewRefresh(added, scenario));
    expect(refreshed.blocking).toBe(true);
    expect(refreshed.nonDerivable[0].id).toBe("N");
  });
});

describe("explicit conversion and leave assistance", () => {
  const genericArray: ShiftCountPreference = {
    type: SHIFT_COUNT,
    description: "Advanced",
    person: ["P1"],
    countDates: [ALL],
    countShiftTypes: ["D", "N"],
    countShiftTypeCoefficients: [["D", 9], ["N", 11]],
    expression: ["x >= T", "x <= T", "x = T"],
    target: [1, 8, 4],
    weight: 7,
  };

  it("previews generic conversion without mutation and retains valid concrete overrides", () => {
    const before = structuredClone(genericArray);
    const preview = valueOf(previewGenericToContractedHours(
      genericArray,
      { policy: "exact", totalHours: 160 },
      scenario,
    ));

    expect(genericArray).toEqual(before);
    expect(preview.source).toEqual(before);
    expect(preview.replacementDraft.countShiftTypeCoefficients).toEqual([
      ["D", 9],
      ["N", 11],
    ]);
    expect(preview.changes.map(change => change.field)).toEqual([
      "hoursContract",
      "expression",
      "target",
      "weight",
      "countShiftTypeCoefficients",
    ]);
    expect(valueOf(confirmGenericToContractedHours(preview)).target).toBe(320);
  });

  it("derives only when conversion explicitly requests it", () => {
    const preview = valueOf(previewGenericToContractedHours(
      genericArray,
      { policy: "exact", totalHours: 160 },
      scenario,
      { deriveCoefficients: true },
    ));
    expect(preview.replacementDraft.countShiftTypeCoefficients).toEqual([
      ["D", 16],
      ["N", 11],
    ]);
  });

  it("removes only metadata when converting back to generic", () => {
    const range = valueOf(compileContractedHours({
      person: ["P1"],
      countDates: [ALL],
      countShiftTypes: ["D"],
      target: { policy: "range", minimumHours: 150, maximumHours: 170 },
    }, scenario));
    const generic = convertContractedHoursToGeneric(range);

    expect(generic).not.toHaveProperty("hoursContract");
    expect(generic).toEqual({
      ...range,
      hoursContract: undefined,
    });
    expect(generic.expression).toEqual(["x >= T", "x <= T"]);
    expect(generic.target).toEqual([300, 340]);
    expect(range.hoursContract).toEqual({ unit: "half-hour", policy: "range" });
  });

  it("reports current expanded LEAVE credit without turning failures into warnings", () => {
    expect(getContractedHoursLeaveCreditOutcome(
      scenario,
      compileExact([LEAVE]),
    ).status).toBe("credited");
    expect(getContractedHoursLeaveCreditOutcome(
      scenario,
      compileExact(["D"]),
    ).status).toBe("uncredited");
    expect(getContractedHoursLeaveCreditOutcome(
      scenario,
      genericArray,
    ).status).toBe("not-applicable");

    const invalid = {
      ...compileExact(),
      countShiftTypes: ["Missing"],
    };
    expect(getContractedHoursLeaveCreditOutcome(scenario, invalid).status).toBe("unknown");
  });
});
