/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 */

import {
  Group,
  Item,
  Preference,
  ShiftCountPreference,
  SHIFT_COUNT,
} from "@/types/scheduling";
import {
  HALF_HOUR_UNIT_MINUTES,
  LEAVE_CREDIT_HALF_HOUR_UNITS,
} from "@/utils/countShiftTypeCoefficients";
import { ALL, LEAVE, OFF } from "@/utils/keywords";

const OFF_SENTINEL = -1;
const LEAVE_SENTINEL = -2;

export interface ContractedHoursShiftTypes {
  items: Item[];
  groups: Group[];
}

export interface ContractedHoursScenario {
  shiftTypes: ContractedHoursShiftTypes;
}

export interface ExactContractedHoursPreference
  extends Omit<ShiftCountPreference, "hoursContract" | "expression" | "target"> {
  hoursContract: { unit: "half-hour"; policy: "exact" };
  expression: "x = T";
  target: number;
}

export interface RangeContractedHoursPreference
  extends Omit<ShiftCountPreference, "hoursContract" | "expression" | "target"> {
  hoursContract: { unit: "half-hour"; policy: "range" };
  expression: ["x >= T", "x <= T"];
  target: [number, number];
}

export type ContractedHoursPreference =
  | ExactContractedHoursPreference
  | RangeContractedHoursPreference;

export type ContractedHoursDraftCoefficient = [string, number | ""];

export type ContractedHoursDraft = Omit<
  ContractedHoursPreference,
  "countShiftTypeCoefficients"
> & {
  countShiftTypeCoefficients: ContractedHoursDraftCoefficient[];
};

export type ContractedHoursErrorCode =
  | "group_reference"
  | "unknown_selector"
  | "empty_selectors"
  | "empty_expansion"
  | "off_not_allowed"
  | "invalid_marker"
  | "invalid_weight"
  | "invalid_expression"
  | "invalid_target"
  | "invalid_range"
  | "invalid_coefficient"
  | "non_concrete_coefficient"
  | "unknown_coefficient"
  | "duplicate_coefficient"
  | "missing_coefficient"
  | "extra_coefficient"
  | "non_derivable_coefficient";

export interface ContractedHoursError {
  code: ContractedHoursErrorCode;
  message: string;
  path?: string;
  preferenceIndex?: number;
}

export type ContractedHoursResult<T> =
  | { ok: true; value: T }
  | { ok: false; error: ContractedHoursError };

export interface ContractedHoursExpansion {
  persistedSelectorOrder: string[];
  semanticIds: string[];
  displayIds: string[];
}

interface ShiftTypeMap {
  indicesById: Map<string, number[]>;
  groupIds: Set<string>;
  items: Item[];
}

function failure<T>(
  code: ContractedHoursErrorCode,
  message: string,
  path?: string,
): ContractedHoursResult<T> {
  return { ok: false, error: { code, message, ...(path ? { path } : {}) } };
}

function atPreference<T>(
  result: ContractedHoursResult<T>,
  preferenceIndex: number,
): ContractedHoursResult<T> {
  if (result.ok) {
    return result;
  }

  const path = result.error.path;
  return {
    ok: false,
    error: {
      ...result.error,
      preferenceIndex,
      path: path?.startsWith("shiftTypes.")
        ? path
        : `preferences[${preferenceIndex}]${path ? `.${path}` : ""}`,
    },
  };
}

function pythonString(value: string): string {
  return `'${value.replaceAll("\\", "\\\\").replaceAll("'", "\\'")}'`;
}

function buildShiftTypeMap(
  shiftTypes: ContractedHoursShiftTypes,
): ContractedHoursResult<ShiftTypeMap> {
  const workedItems = shiftTypes.items.filter(item =>
    !item.isAutoGenerated
    && item.id !== ALL
    && item.id !== OFF
    && item.id !== LEAVE
  );
  const userGroups = shiftTypes.groups.filter(group => !group.isAutoGenerated);
  const indicesById = new Map<string, number[]>();
  workedItems.forEach((item, index) => indicesById.set(item.id, [index]));
  indicesById.set(ALL, workedItems.map((_, index) => index));
  indicesById.set(OFF, [OFF_SENTINEL]);
  indicesById.set(LEAVE, [LEAVE_SENTINEL]);

  for (const group of userGroups) {
    const indices = new Set<number>();
    for (const member of group.members) {
      const memberIndices = indicesById.get(member);
      if (!memberIndices) {
        return failure(
          "group_reference",
          `Shift type group ${pythonString(group.id)} references undefined shift type or group ID ${pythonString(member)} (forward reference, cycle, or unknown id).`,
          `shiftTypes.groups.${group.id}.members`,
        );
      }
      memberIndices.forEach(index => indices.add(index));
    }
    indicesById.set(group.id, [...indices].sort((a, b) => a - b));
  }

  return {
    ok: true,
    value: {
      indicesById,
      groupIds: new Set(userGroups.map(group => group.id)),
      items: workedItems,
    },
  };
}

function expandWithMap(
  selectors: string[],
  shiftTypeMap: ShiftTypeMap,
): ContractedHoursResult<ContractedHoursExpansion> {
  if (selectors.length === 0) {
    return failure(
      "empty_selectors",
      "A contracted-hours shift count requires non-empty countShiftTypes.",
      "countShiftTypes",
    );
  }

  const expanded = new Set<number>();
  for (const selector of selectors) {
    const indices = shiftTypeMap.indicesById.get(selector);
    if (!indices) {
      return failure(
        "unknown_selector",
        `Unknown shift type ID: ${selector}`,
        "countShiftTypes",
      );
    }
    indices.forEach(index => expanded.add(index));
  }

  const semanticIndices = [...expanded].sort((a, b) => a - b);
  if (semanticIndices.length === 0) {
    return failure(
      "empty_expansion",
      "A contracted-hours shift count must select at least one shift type.",
      "countShiftTypes",
    );
  }
  if (expanded.has(OFF_SENTINEL)) {
    return failure(
      "off_not_allowed",
      "'OFF' is not allowed in a contracted-hours shift count.",
      "countShiftTypes",
    );
  }

  const semanticIds = semanticIndices.map(index =>
    index === LEAVE_SENTINEL ? LEAVE : shiftTypeMap.items[index].id
  );
  const displayIds = [
    ...shiftTypeMap.items
      .filter((_, index) => expanded.has(index))
      .map(item => item.id),
    ...(expanded.has(LEAVE_SENTINEL) ? [LEAVE] : []),
  ];

  return {
    ok: true,
    value: {
      persistedSelectorOrder: [...selectors],
      semanticIds,
      displayIds,
    },
  };
}

export function expandContractedHoursShiftTypes(
  shiftTypes: ContractedHoursShiftTypes,
  selectors: string[],
): ContractedHoursResult<ContractedHoursExpansion> {
  const shiftTypeMap = buildShiftTypeMap(shiftTypes);
  if (!shiftTypeMap.ok) {
    return shiftTypeMap;
  }
  return expandWithMap(selectors, shiftTypeMap.value);
}

export type ContractedHoursTargetInput =
  | { policy: "exact"; totalHours: number }
  | { policy: "range"; minimumHours: number; maximumHours: number };

export interface ContractedHoursPolicyFields {
  hoursContract:
    | { unit: "half-hour"; policy: "exact" }
    | { unit: "half-hour"; policy: "range" };
  expression: "x = T" | ["x >= T", "x <= T"];
  target: number | [number, number];
  weight: number;
}

export function hoursToHalfHourUnits(
  hours: number,
  path = "target",
): ContractedHoursResult<number> {
  const units = hours * 2;
  if (!Number.isFinite(hours) || hours < 0 || !Number.isInteger(units)) {
    return failure(
      "invalid_target",
      "Contracted hours must be a non-negative total in 30-minute steps.",
      path,
    );
  }
  return { ok: true, value: units };
}

export function compileContractedHoursPolicy(
  input: ContractedHoursTargetInput,
): ContractedHoursResult<ContractedHoursPolicyFields> {
  if (input.policy === "exact") {
    const target = hoursToHalfHourUnits(input.totalHours);
    if (!target.ok) {
      return target;
    }
    return {
      ok: true,
      value: {
        hoursContract: { unit: "half-hour", policy: "exact" },
        expression: "x = T",
        target: target.value,
        weight: Number.POSITIVE_INFINITY,
      },
    };
  }

  const minimum = hoursToHalfHourUnits(input.minimumHours, "target.0");
  if (!minimum.ok) {
    return minimum;
  }
  const maximum = hoursToHalfHourUnits(input.maximumHours, "target.1");
  if (!maximum.ok) {
    return maximum;
  }
  if (minimum.value > maximum.value) {
    return failure(
      "invalid_range",
      "Contracted-hours range minimum must not exceed maximum.",
      "target",
    );
  }
  return {
    ok: true,
    value: {
      hoursContract: { unit: "half-hour", policy: "range" },
      expression: ["x >= T", "x <= T"],
      target: [minimum.value, maximum.value],
      weight: Number.POSITIVE_INFINITY,
    },
  };
}

function deriveCoefficient(id: string, shiftTypes: ContractedHoursShiftTypes): number | undefined {
  if (id === LEAVE) {
    return LEAVE_CREDIT_HALF_HOUR_UNITS;
  }
  const durationMinutes = shiftTypes.items.find(item => item.id === id)?.durationMinutes;
  if (
    typeof durationMinutes !== "number"
    || !Number.isInteger(durationMinutes)
    || durationMinutes <= 0
    || durationMinutes % HALF_HOUR_UNIT_MINUTES !== 0
  ) {
    return undefined;
  }
  return durationMinutes / HALF_HOUR_UNIT_MINUTES;
}

function validExistingCoefficient(
  coefficients: readonly ContractedHoursDraftCoefficient[],
  id: string,
): number | undefined {
  const matches = coefficients.filter(([coefficientId]) => coefficientId === id);
  if (matches.length !== 1) {
    return undefined;
  }
  const value = matches[0][1];
  return typeof value === "number" && Number.isInteger(value) && value >= 1
    ? value
    : undefined;
}

export interface ContractedHoursCompileInput {
  description?: string;
  person: string[];
  countDates: string[];
  countShiftTypes: string[];
  target: ContractedHoursTargetInput;
  existingCoefficients?: ContractedHoursDraftCoefficient[];
  deriveCoefficients?: boolean;
}

function buildContractedHoursDraft(
  input: ContractedHoursCompileInput,
  scenario: ContractedHoursScenario,
): ContractedHoursResult<ContractedHoursDraft> {
  const policy = compileContractedHoursPolicy(input.target);
  if (!policy.ok) {
    return policy;
  }
  const expansion = expandContractedHoursShiftTypes(
    scenario.shiftTypes,
    input.countShiftTypes,
  );
  if (!expansion.ok) {
    return expansion;
  }

  const existing = input.existingCoefficients ?? [];
  const shouldDerive = input.deriveCoefficients !== false;
  const coefficients = expansion.value.displayIds.map((id): ContractedHoursDraftCoefficient => {
    const derived = shouldDerive ? deriveCoefficient(id, scenario.shiftTypes) : undefined;
    return [id, derived ?? validExistingCoefficient(existing, id) ?? ""];
  });

  return {
    ok: true,
    value: {
      type: SHIFT_COUNT,
      ...(input.description !== undefined ? { description: input.description } : {}),
      person: [...input.person],
      countDates: [...input.countDates],
      countShiftTypes: [...input.countShiftTypes],
      countShiftTypeCoefficients: coefficients,
      ...policy.value,
    } as ContractedHoursDraft,
  };
}

export function compileContractedHours(
  input: ContractedHoursCompileInput,
  scenario: ContractedHoursScenario,
): ContractedHoursResult<ContractedHoursPreference> {
  const draft = buildContractedHoursDraft(input, scenario);
  if (!draft.ok) {
    return draft;
  }
  const missing = draft.value.countShiftTypeCoefficients.find(([, value]) => value === "");
  if (missing) {
    return failure(
      "non_derivable_coefficient",
      `Shift type '${missing[0]}' has no derivable working time or valid explicit coefficient.`,
      `countShiftTypeCoefficients.${missing[0]}`,
    );
  }
  return {
    ok: true,
    value: draft.value as ContractedHoursPreference,
  };
}

function validatePolicy(
  preference: ShiftCountPreference,
): ContractedHoursResult<ContractedHoursPreference> {
  const marker = preference.hoursContract as { unit?: unknown; policy?: unknown };
  if (
    marker.unit !== "half-hour"
    || (marker.policy !== "exact" && marker.policy !== "range")
    || Object.keys(marker).length !== 2
  ) {
    return failure(
      "invalid_marker",
      "hoursContract must contain exactly unit 'half-hour' and policy 'exact' or 'range'.",
      "hoursContract",
    );
  }
  if (preference.weight !== Number.POSITIVE_INFINITY) {
    return failure(
      "invalid_weight",
      `A '${marker.policy}' contracted-hours shift count must use weight '.inf', but got ${String(preference.weight)}.`,
      "weight",
    );
  }

  if (marker.policy === "exact") {
    if (preference.expression !== "x = T") {
      return failure(
        "invalid_expression",
        "An exact contracted-hours shift count must use expression 'x = T'.",
        "expression",
      );
    }
    if (Array.isArray(preference.target)) {
      return failure(
        "invalid_target",
        "An exact contracted-hours shift count must use a scalar target.",
        "target",
      );
    }
    if (!Number.isInteger(preference.target)) {
      return failure(
        "invalid_target",
        `Contracted-hours target must be an integer, but got ${String(preference.target)}.`,
        "target",
      );
    }
    if (preference.target < 0) {
      return failure(
        "invalid_target",
        `Contracted-hours target must be non-negative, but got ${String(preference.target)}.`,
        "target",
      );
    }
  } else {
    if (
      !Array.isArray(preference.expression)
      || preference.expression.length !== 2
      || preference.expression[0] !== "x >= T"
      || preference.expression[1] !== "x <= T"
    ) {
      return failure(
        "invalid_expression",
        "A range contracted-hours shift count must use expression ['x >= T', 'x <= T'].",
        "expression",
      );
    }
    if (!Array.isArray(preference.target) || preference.target.length !== 2) {
      return failure(
        "invalid_target",
        "A range contracted-hours shift count must use a two-element [minimum, maximum] target.",
        "target",
      );
    }
    const [minimum, maximum] = preference.target;
    if (!Number.isInteger(minimum) || !Number.isInteger(maximum)) {
      return failure(
        "invalid_target",
        `Contracted-hours range targets must be integers, but got [${minimum}, ${maximum}].`,
        "target",
      );
    }
    if (minimum < 0 || maximum < 0) {
      return failure(
        "invalid_target",
        `Contracted-hours range targets must be non-negative, but got [${minimum}, ${maximum}].`,
        "target",
      );
    }
    if (minimum > maximum) {
      return failure(
        "invalid_range",
        `Contracted-hours range minimum must not exceed maximum, but got [${minimum}, ${maximum}].`,
        "target",
      );
    }
  }

  return { ok: true, value: preference as ContractedHoursPreference };
}

function validateCoverage(
  preference: ShiftCountPreference,
  shiftTypeMap: ShiftTypeMap,
): ContractedHoursResult<ContractedHoursExpansion> {
  const expansion = expandWithMap(preference.countShiftTypes, shiftTypeMap);
  if (!expansion.ok) {
    return expansion;
  }

  const coefficientEntries = preference.countShiftTypeCoefficients ?? [];
  const coefficientIndices = new Set<number>();
  for (let index = 0; index < coefficientEntries.length; index += 1) {
    const [id, coefficient] = coefficientEntries[index];
    if (!Number.isInteger(coefficient)) {
      return failure(
        "invalid_coefficient",
        `Contracted-hours coefficient for '${id}' must be an integer.`,
        `countShiftTypeCoefficients.${index}.1`,
      );
    }
    if (coefficient < 1) {
      return failure(
        "invalid_coefficient",
        `Contracted-hours coefficient for '${id}' must be at least 1.`,
        `countShiftTypeCoefficients.${index}.1`,
      );
    }
    if (id === OFF) {
      return failure(
        "off_not_allowed",
        "'OFF' is not allowed in a contracted-hours shift count.",
        `countShiftTypeCoefficients.${index}.0`,
      );
    }
    if (id === ALL || shiftTypeMap.groupIds.has(id)) {
      return failure(
        "non_concrete_coefficient",
        `Contracted-hours coefficient '${id}' must be a concrete shift type or 'LEAVE', not a group or 'ALL'.`,
        `countShiftTypeCoefficients.${index}.0`,
      );
    }
    const indices = shiftTypeMap.indicesById.get(id);
    if (!indices) {
      return failure(
        "unknown_coefficient",
        `Unknown shift type ID: ${id}`,
        `countShiftTypeCoefficients.${index}.0`,
      );
    }
    const coefficientIndex = indices[0];
    if (coefficientIndices.has(coefficientIndex)) {
      return failure(
        "duplicate_coefficient",
        `Duplicate contracted-hours coefficient for '${id}'.`,
        `countShiftTypeCoefficients.${index}.0`,
      );
    }
    coefficientIndices.add(coefficientIndex);
  }

  const expandedIndices = new Set(
    expansion.value.semanticIds.map(id => shiftTypeMap.indicesById.get(id)![0]),
  );
  const missingId = expansion.value.semanticIds.find(id =>
    !coefficientIndices.has(shiftTypeMap.indicesById.get(id)![0])
  );
  if (missingId !== undefined) {
    return failure(
      "missing_coefficient",
      `A contracted-hours shift count is missing the explicit coefficient for '${missingId}'.`,
      "countShiftTypeCoefficients",
    );
  }
  const extraId = coefficientEntries.find(([id]) => {
    const index = shiftTypeMap.indicesById.get(id)?.[0];
    return index !== undefined && !expandedIndices.has(index);
  })?.[0];
  if (extraId !== undefined) {
    return failure(
      "extra_coefficient",
      `The contracted-hours coefficient for '${extraId}' does not correspond to any selected shift type.`,
      "countShiftTypeCoefficients",
    );
  }

  return expansion;
}

export type ContractedHoursValidation =
  | { kind: "generic"; preference: ShiftCountPreference }
  | {
      kind: "contracted-hours";
      preference: ContractedHoursPreference;
      expansion: ContractedHoursExpansion;
    };

export function validateContractedHours(
  scenario: ContractedHoursScenario,
  preference: ShiftCountPreference,
): ContractedHoursResult<ContractedHoursValidation> {
  if (!preference.hoursContract) {
    return { ok: true, value: { kind: "generic", preference } };
  }

  const shiftTypeMap = buildShiftTypeMap(scenario.shiftTypes);
  if (!shiftTypeMap.ok) {
    return shiftTypeMap;
  }
  const policy = validatePolicy(preference);
  if (!policy.ok) {
    return policy;
  }
  const coverage = validateCoverage(preference, shiftTypeMap.value);
  if (!coverage.ok) {
    return coverage;
  }
  return {
    ok: true,
    value: {
      kind: "contracted-hours",
      preference: policy.value,
      expansion: coverage.value,
    },
  };
}

export function validateContractedHoursScenario(
  scenario: ContractedHoursScenario & { preferences: Preference[] },
): ContractedHoursResult<ContractedHoursValidation[]> {
  const shiftCounts = scenario.preferences
    .map((preference, preferenceIndex) => ({ preference, preferenceIndex }))
    .filter(
      (entry): entry is { preference: ShiftCountPreference; preferenceIndex: number } =>
        entry.preference.type === SHIFT_COUNT,
    );
  const marked = shiftCounts.filter(({ preference }) => preference.hoursContract);
  if (marked.length === 0) {
    return {
      ok: true,
      value: shiftCounts.map(({ preference }) => ({ kind: "generic", preference })),
    };
  }
  const shiftTypeMap = buildShiftTypeMap(scenario.shiftTypes);
  if (!shiftTypeMap.ok) {
    return atPreference(shiftTypeMap, marked[0].preferenceIndex);
  }

  const values: ContractedHoursValidation[] = [];
  for (const { preference, preferenceIndex } of shiftCounts) {
    if (!preference.hoursContract) {
      values.push({ kind: "generic", preference });
      continue;
    }
    const policy = validatePolicy(preference);
    if (!policy.ok) {
      return atPreference(policy, preferenceIndex);
    }
    const coverage = validateCoverage(preference, shiftTypeMap.value);
    if (!coverage.ok) {
      return atPreference(coverage, preferenceIndex);
    }
    values.push({
      kind: "contracted-hours",
      preference: policy.value,
      expansion: coverage.value,
    });
  }
  return { ok: true, value: values };
}

export interface ContractedHoursRefreshRow {
  id: string;
  before: number | "";
  after: number | "";
  derivable: boolean;
  blocking: boolean;
}

export interface ContractedHoursRefreshPreview {
  originalDraft: ContractedHoursDraft;
  replacementDraft: ContractedHoursDraft;
  expansion: ContractedHoursExpansion;
  added: ContractedHoursRefreshRow[];
  removed: ContractedHoursRefreshRow[];
  changed: ContractedHoursRefreshRow[];
  unchanged: ContractedHoursRefreshRow[];
  nonDerivable: ContractedHoursRefreshRow[];
  blocking: boolean;
}

export function previewRefresh(
  draft: ContractedHoursDraft,
  scenario: ContractedHoursScenario,
): ContractedHoursResult<ContractedHoursRefreshPreview> {
  const expansion = expandContractedHoursShiftTypes(
    scenario.shiftTypes,
    draft.countShiftTypes,
  );
  if (!expansion.ok) {
    return expansion;
  }

  const currentIds = new Set(expansion.value.displayIds);
  const added: ContractedHoursRefreshRow[] = [];
  const changed: ContractedHoursRefreshRow[] = [];
  const unchanged: ContractedHoursRefreshRow[] = [];
  const nonDerivable: ContractedHoursRefreshRow[] = [];

  const nextCoefficients = expansion.value.displayIds.map((id): ContractedHoursDraftCoefficient => {
    const matching = draft.countShiftTypeCoefficients.filter(([existingId]) => existingId === id);
    const before = matching[0]?.[1] ?? "";
    const derived = deriveCoefficient(id, scenario.shiftTypes);
    const existing = validExistingCoefficient(draft.countShiftTypeCoefficients, id);
    const after = derived ?? existing ?? "";
    const row: ContractedHoursRefreshRow = {
      id,
      before,
      after,
      derivable: derived !== undefined,
      blocking: after === "",
    };

    if (matching.length === 0) {
      added.push(row);
    } else if (matching.length !== 1 || before !== after) {
      changed.push(row);
    } else {
      unchanged.push(row);
    }
    if (derived === undefined) {
      nonDerivable.push(row);
    }
    return [id, after];
  });

  const removed = draft.countShiftTypeCoefficients
    .filter(([id]) => !currentIds.has(id))
    .map(([id, value]): ContractedHoursRefreshRow => ({
      id,
      before: value,
      after: "",
      derivable: false,
      blocking: false,
    }));

  return {
    ok: true,
    value: {
      originalDraft: structuredClone(draft),
      replacementDraft: {
        ...structuredClone(draft),
        countShiftTypeCoefficients: nextCoefficients,
      },
      expansion: expansion.value,
      added,
      removed,
      changed,
      unchanged,
      nonDerivable,
      blocking: nextCoefficients.some(([, value]) => value === ""),
    },
  };
}

export interface ContractedHoursRefreshTransaction {
  draft: ContractedHoursDraft;
  undoSnapshot: ContractedHoursDraft;
}

export function confirmRefresh(
  preview: ContractedHoursRefreshPreview,
): ContractedHoursRefreshTransaction {
  return {
    draft: structuredClone(preview.replacementDraft),
    undoSnapshot: structuredClone(preview.originalDraft),
  };
}

export function restoreRefreshSnapshot(
  transaction: ContractedHoursRefreshTransaction,
): ContractedHoursRefreshTransaction {
  return {
    draft: structuredClone(transaction.undoSnapshot),
    undoSnapshot: structuredClone(transaction.draft),
  };
}

export function reconcileContractedHoursDraftSelectors(
  draft: ContractedHoursDraft,
  countShiftTypes: string[],
  scenario: ContractedHoursScenario,
): ContractedHoursResult<ContractedHoursDraft> {
  const expansion = expandContractedHoursShiftTypes(scenario.shiftTypes, countShiftTypes);
  if (!expansion.ok) {
    return expansion;
  }
  return {
    ok: true,
    value: {
      ...structuredClone(draft),
      countShiftTypes: [...countShiftTypes],
      countShiftTypeCoefficients: expansion.value.displayIds.map(id => [
        id,
        validExistingCoefficient(draft.countShiftTypeCoefficients, id) ?? "",
      ]),
    },
  };
}

export interface ContractedHoursConversionField {
  field: "hoursContract" | "expression" | "target" | "weight" | "countShiftTypeCoefficients";
  before: unknown;
  after: unknown;
}

export interface GenericToContractedHoursPreview {
  source: ShiftCountPreference;
  replacementDraft: ContractedHoursDraft;
  changes: ContractedHoursConversionField[];
}

export function previewGenericToContractedHours(
  preference: ShiftCountPreference,
  target: ContractedHoursTargetInput,
  scenario: ContractedHoursScenario,
  options: { deriveCoefficients?: boolean } = {},
): ContractedHoursResult<GenericToContractedHoursPreview> {
  const draft = buildContractedHoursDraft(
    {
      ...(preference.description !== undefined
        ? { description: preference.description }
        : {}),
      person: preference.person,
      countDates: preference.countDates,
      countShiftTypes: preference.countShiftTypes,
      target,
      existingCoefficients: preference.countShiftTypeCoefficients,
      deriveCoefficients: options.deriveCoefficients === true,
    },
    scenario,
  );
  if (!draft.ok) {
    return draft;
  }

  const changes: ContractedHoursConversionField[] = [
    { field: "hoursContract", before: preference.hoursContract, after: draft.value.hoursContract },
    { field: "expression", before: preference.expression, after: draft.value.expression },
    { field: "target", before: preference.target, after: draft.value.target },
    { field: "weight", before: preference.weight, after: draft.value.weight },
    {
      field: "countShiftTypeCoefficients",
      before: preference.countShiftTypeCoefficients,
      after: draft.value.countShiftTypeCoefficients,
    },
  ];
  return {
    ok: true,
    value: {
      source: structuredClone(preference),
      replacementDraft: draft.value,
      changes,
    },
  };
}

export function confirmGenericToContractedHours(
  preview: GenericToContractedHoursPreview,
): ContractedHoursResult<ContractedHoursPreference> {
  const missing = preview.replacementDraft.countShiftTypeCoefficients.find(
    ([, value]) => value === "",
  );
  if (missing) {
    return failure(
      "non_derivable_coefficient",
      `Shift type '${missing[0]}' requires an explicit positive integer coefficient.`,
      `countShiftTypeCoefficients.${missing[0]}`,
    );
  }
  return {
    ok: true,
    value: structuredClone(preview.replacementDraft) as ContractedHoursPreference,
  };
}

export function convertContractedHoursToGeneric(
  preference: ContractedHoursPreference,
): ShiftCountPreference {
  const generic = structuredClone(preference) as ShiftCountPreference;
  delete generic.hoursContract;
  return generic;
}

export type ContractedHoursLeaveCreditOutcome =
  | { status: "not-applicable" }
  | { status: "unknown"; error: ContractedHoursError }
  | { status: "credited"; expansion: ContractedHoursExpansion }
  | { status: "uncredited"; expansion: ContractedHoursExpansion };

export function getContractedHoursLeaveCreditOutcome(
  scenario: ContractedHoursScenario,
  preference: ShiftCountPreference,
): ContractedHoursLeaveCreditOutcome {
  if (!preference.hoursContract) {
    return { status: "not-applicable" };
  }
  const expansion = expandContractedHoursShiftTypes(
    scenario.shiftTypes,
    preference.countShiftTypes,
  );
  if (!expansion.ok) {
    return { status: "unknown", error: expansion.error };
  }
  return expansion.value.semanticIds.includes(LEAVE)
    ? { status: "credited", expansion: expansion.value }
    : { status: "uncredited", expansion: expansion.value };
}
