/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 */

import { execFileSync } from "node:child_process";
import path from "node:path";

import {
  addAutoGeneratedToState,
  filterAutoGeneratedState,
} from "@/hooks/schedulingGeneratedData";
import { SchedulingState } from "@/hooks/schedulingState";
import {
  compileContractedHours,
  ContractedHoursResult,
} from "@/utils/contractedHours";
import { ALL, LEAVE } from "@/utils/keywords";
import { generateYamlFromState } from "@/utils/yamlGenerator";

function valueOf<T>(result: ContractedHoursResult<T>): T {
  if (!result.ok) {
    throw new Error(result.error.message);
  }
  return result.value;
}

const coreDirectory = path.resolve(process.cwd(), "../core");
const python = path.join(coreDirectory, ".venv/bin/python");
const verificationScript = `
import json
import sys

import nurse_scheduling
from nurse_scheduling.loader import load_data

payload = sys.stdin.buffer.read()
data = load_data(payload)
contract = next(pref for pref in data.preferences if pref.type == "shift count")
_frame, _solution, _score, status, _cell_export_info = nurse_scheduling.schedule(payload)
print(json.dumps({
    "policy": contract.hoursContract.policy,
    "expression": contract.expression,
    "target": contract.target,
    "selectors": contract.countShiftTypes,
    "coefficients": contract.countShiftTypeCoefficients,
    "weightIsInfinite": contract.weight == float("inf"),
    "status": status,
}))
`;

function generateScenario(policy: "exact" | "range"): string {
  const shiftTypes = {
    items: [{ id: "D", description: "Day", durationMinutes: 480 }],
    groups: [],
  };
  const contract = valueOf(compileContractedHours({
    description: policy,
    person: ["P1"],
    countDates: [ALL],
    countShiftTypes: ["D"],
    target: policy === "exact"
      ? { policy: "exact", totalHours: 0 }
      : { policy: "range", minimumHours: 0, maximumHours: 8 },
  }, { shiftTypes }));

  return generateYamlFromState({
    apiVersion: "alpha",
    description: `Generated ${policy} contracted hours`,
    dates: {
      range: {
        startDate: new Date("2026-07-01T00:00:00.000Z"),
        endDate: new Date("2026-07-01T00:00:00.000Z"),
      },
      items: [],
      groups: [],
    },
    people: {
      items: [{ id: "P1", description: "", history: [] }],
      groups: [],
    },
    shiftTypes,
    preferences: [
      { type: "at most one shift per day" },
      contract,
    ],
  });
}

function generateNormalizedGroupScenario(): string {
  const rawState: SchedulingState = {
    apiVersion: "alpha",
    description: "Normalized ALL group parity",
    dates: {
      range: {
        startDate: new Date("2026-07-01T00:00:00.000Z"),
        endDate: new Date("2026-07-01T00:00:00.000Z"),
      },
      items: [],
      groups: [],
    },
    people: {
      items: [{ id: "P1", description: "", history: [] }],
      groups: [],
    },
    shiftTypes: {
      items: [{ id: "D", description: "Day", durationMinutes: 480 }],
      groups: [
        { id: "Work", description: "", members: [ALL, LEAVE] },
        { id: "NestedWork", description: "", members: ["Work"] },
      ],
    },
    preferences: [{ type: "at most one shift per day" }],
  };
  const normalized = addAutoGeneratedToState(rawState);
  const contract = valueOf(compileContractedHours({
    description: "Nested normalized group",
    person: ["P1"],
    countDates: [ALL],
    countShiftTypes: ["NestedWork"],
    target: { policy: "exact", totalHours: 0 },
  }, normalized));
  const filtered = filterAutoGeneratedState({
    ...normalized,
    preferences: [...normalized.preferences, contract],
  });
  return generateYamlFromState(filtered);
}

describe("generated Contracted Hours YAML backend integration", () => {
  it.each([
    ["exact", "x = T", 0],
    ["range", ["x >= T", "x <= T"], [0, 16]],
  ] as const)(
    "loads and schedules the generated %s policy through Pydantic",
    (policy, expression, target) => {
      const output = execFileSync(
        python,
        ["-c", verificationScript],
        {
          cwd: coreDirectory,
          input: generateScenario(policy),
          encoding: "utf8",
        },
      );

      expect(JSON.parse(output)).toEqual({
        policy,
        expression,
        target,
        selectors: ["D"],
        coefficients: [["D", 16]],
        weightIsInfinite: true,
        status: "OPTIMAL",
      });
    },
  );

  it("matches backend expansion after normalized state is filtered for YAML", () => {
    const output = execFileSync(
      python,
      ["-c", verificationScript],
      {
        cwd: coreDirectory,
        input: generateNormalizedGroupScenario(),
        encoding: "utf8",
      },
    );

    expect(JSON.parse(output)).toEqual({
      policy: "exact",
      expression: "x = T",
      target: 0,
      selectors: ["NestedWork"],
      coefficients: [["D", 16], ["LEAVE", 16]],
      weightIsInfinite: true,
      status: "OPTIMAL",
    });
  });
});
