/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// This test is mostly AI generated.

import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { act } from 'react';
import OptimizeAndExportPage from '@/app/optimize-and-export/page';
import {
  ContractedHoursBoundaryError,
  ContractedHoursDiagnostic,
} from '@/utils/contractedHoursBoundary';

const mockUseSchedulingData = vi.hoisted(() => vi.fn());
const mockGenerateYamlFromState = vi.hoisted(() => vi.fn());
const mockRestorePeopleIdsInXlsx = vi.hoisted(() => vi.fn());
const mockCurrentAppVersion = vi.hoisted(() => ({ value: 'frontend-test' }));

vi.mock('@/hooks/useSchedulingData', () => ({
  useSchedulingData: mockUseSchedulingData,
}));

vi.mock('@/utils/yamlGenerator', () => ({
  generateYamlFromState: mockGenerateYamlFromState,
}));

vi.mock('@/utils/restorePeopleIdsInXlsx', () => ({
  restorePeopleIdsInXlsx: mockRestorePeopleIdsInXlsx,
}));

vi.mock('@/utils/version', () => ({
  get CURRENT_APP_VERSION() {
    return mockCurrentAppVersion.value;
  },
  compareVersionsDescending: vi.fn(() => 0),
  parseVersionParts: (version: string) => ({
    dirty: version.endsWith('-dirty'),
  }),
}));

// The backend URL is resolved from NEXT_PUBLIC_BACKEND_API_URL at build time; it
// is unset under test so the app falls back to the local default.
const BACKEND_API_URL = 'http://localhost:8000';

class MockEventSource {
  static instances: MockEventSource[] = [];

  listeners = new Map<string, Array<(event: MessageEvent) => void>>();
  url: string;
  close = vi.fn();

  constructor(url: string) {
    this.url = url;
    MockEventSource.instances.push(this);
  }

  addEventListener(type: string, listener: (event: MessageEvent) => void) {
    this.listeners.set(type, [...(this.listeners.get(type) ?? []), listener]);
  }

  emit(type: string, data: unknown) {
    const event = new MessageEvent(type, {
      data: typeof data === 'string' ? data : JSON.stringify(data),
    });
    this.listeners.get(type)?.forEach(listener => listener(event));
  }
}

const createSchedulingData = (overrides = {}) => ({
  apiVersionData: 'alpha',
  descriptionData: 'baseline',
  dateData: {
    range: { startDate: new Date('2026-09-01'), endDate: new Date('2026-09-01') },
    items: [{ id: '01', description: '' }],
    groups: [],
  },
  peopleData: { items: [{ id: 'P1', description: '', history: [] }], groups: [], history: [] },
  shiftTypeData: { items: [{ id: 'D', description: '' }], groups: [] },
  preferences: [],
  exportData: { formatting: [] },
  filterAutoGeneratedState: vi.fn(state => state),
  ...overrides,
});

const healthyResponse = (overrides: Partial<{
  status: string;
  api_version: string;
  app_version: string;
}> = {}) => ({
  ok: true,
  json: vi.fn().mockResolvedValue({
    status: 'ready',
    api_version: 'alpha',
    app_version: 'frontend-test',
    ...overrides,
  }),
});

// Queue the mount-time health check so the backend resolves online, then let the
// caller chain the optimize/download responses that follow.
const queueInitialLocalSelection = (fetchMock: ReturnType<typeof vi.fn>) => {
  fetchMock.mockResolvedValueOnce(healthyResponse());
  return fetchMock;
};

const contractedHoursDiagnostic = (
  boundary: ContractedHoursDiagnostic['boundary'],
): ContractedHoursDiagnostic => ({
  boundary,
  code: 'missing_coefficient',
  message: "Contracted Hours preference 2 (Monthly contract): A contracted-hours shift count is missing the explicit coefficient for 'E'.",
  detail: "A contracted-hours shift count is missing the explicit coefficient for 'E'.",
  path: 'preferences[1].countShiftTypeCoefficients',
  preferenceIndex: 1,
  preferenceDescription: 'Monthly contract',
  repair: 'Open Contracted Hours, repair or refresh the rule, then retry this action.',
  navigationHref: '/shift-counts',
  navigationLabel: 'Review Contracted Hours',
});

const optimizeJobResponse = ({
  id,
  state = 'queued',
  queuePosition = null,
  outcome = null,
  score = null,
  solverStatus = null,
  error = null,
  earlyCompletionAvailable = state === 'running',
}: {
  id: string;
  state?: 'queued' | 'running' | 'cancelling' | 'completed' | 'cancelled' | 'failed';
  queuePosition?: number | null;
  outcome?: 'optimal' | 'feasible' | 'infeasible' | null;
  score?: number | null;
  solverStatus?: string | null;
  error?: string | null;
  earlyCompletionAvailable?: boolean;
}) => {
  const terminal = ['completed', 'cancelled', 'failed'].includes(state);
  const scheduleReady = state === 'completed' && outcome !== null && outcome !== 'infeasible';
  return {
    id,
    state,
    terminal,
    queue_position: queuePosition,
    result: outcome && solverStatus ? {
      outcome,
      score,
      solver_status: solverStatus,
      termination_reason: null,
    } : null,
    error: error ? { code: state === 'cancelled' ? 'cancelled' : 'optimization_failed', message: error } : null,
    controls: {
      cancellable: !terminal && state !== 'cancelling',
      early_completion_available: earlyCompletionAvailable && !terminal,
    },
    links: {
      self: `/optimize/${id}`,
      events: `/optimize/${id}/events`,
      cancellation: `/optimize/${id}/cancel`,
      early_completion: `/optimize/${id}/finish-now`,
      schedule: scheduleReady ? `/optimize/${id}/xlsx` : null,
    },
  };
};

describe('OptimizeAndExportPage error handling', () => {
  beforeEach(() => {
    vi.restoreAllMocks();
    MockEventSource.instances = [];
    mockGenerateYamlFromState.mockReturnValue('apiVersion: alpha\ndescription: baseline\n');
    mockRestorePeopleIdsInXlsx.mockClear();
    mockRestorePeopleIdsInXlsx.mockImplementation(async blob => blob);
    mockUseSchedulingData.mockReturnValue(createSchedulingData());
    mockCurrentAppVersion.value = 'frontend-test';
    vi.stubGlobal('fetch', vi.fn());
    vi.stubGlobal('EventSource', undefined);
    vi.spyOn(URL, 'createObjectURL').mockReturnValue('blob:mock');
    vi.spyOn(URL, 'revokeObjectURL').mockImplementation(() => undefined);
  });

  it('surfaces raw non-JSON error bodies from the backend', async () => {
    const user = userEvent.setup();
    queueInitialLocalSelection(fetch as unknown as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce({
        ok: false,
        status: 503,
        text: vi.fn().mockResolvedValue('service unavailable'),
      });

    render(<OptimizeAndExportPage />);
    await screen.findByText('Server: Online');
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));

    await expect(screen.findByText('Server error (503): service unavailable')).resolves.toBeInTheDocument();
  });

  it('falls back to the raw JSON text when the backend error body has no detail field', async () => {
    const user = userEvent.setup();
    queueInitialLocalSelection(fetch as unknown as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce({
        ok: false,
        status: 422,
        text: vi.fn().mockResolvedValue(JSON.stringify({ error: 'validation failed' })),
      });

    render(<OptimizeAndExportPage />);
    await screen.findByText('Server: Online');
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));

    await expect(screen.findByText('Server error (422): {"error":"validation failed"}')).resolves.toBeInTheDocument();
  });

  it('surfaces messages from the backend application error envelope', async () => {
    const user = userEvent.setup();
    queueInitialLocalSelection(fetch as unknown as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce({
        ok: false,
        status: 429,
        text: vi.fn().mockResolvedValue(JSON.stringify({
          error: { code: 'job_capacity_exceeded', message: 'Too many jobs are queued or running' },
        })),
      });

    render(<OptimizeAndExportPage />);
    await screen.findByText('Server: Online');
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));

    await expect(screen.findByText('Server error (429): Too many jobs are queued or running')).resolves.toBeInTheDocument();
  });

  it('keeps showing the raw response text when JSON parsing itself fails', async () => {
    const user = userEvent.setup();
    queueInitialLocalSelection(fetch as unknown as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce({
        ok: false,
        status: 500,
        text: vi.fn().mockResolvedValue('{bad json'),
      });

    render(<OptimizeAndExportPage />);
    await screen.findByText('Server: Online');
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));

    await expect(screen.findByText('Server error (500): {bad json')).resolves.toBeInTheDocument();
    expect(screen.queryByText(/check that your frontend and backend versions match/i)).not.toBeInTheDocument();
  });

  it('does not show generic version compatibility guidance', () => {
    (fetch as unknown as ReturnType<typeof vi.fn>).mockImplementation(() => new Promise(() => undefined));

    render(<OptimizeAndExportPage />);

    expect(screen.queryByText(/this project is in active development/i)).not.toBeInTheDocument();
    expect(screen.queryByText(/check that your frontend and backend versions match/i)).not.toBeInTheDocument();
  });

  it('shows backend readiness and version status from the configured info endpoint', async () => {
    (fetch as unknown as ReturnType<typeof vi.fn>).mockResolvedValue({
      ok: true,
      json: vi.fn().mockResolvedValue({
        status: 'ready',
        api_version: 'alpha',
        app_version: 'v-test',
      }),
    });

    render(<OptimizeAndExportPage />);

    await expect(screen.findByText('Server: Online')).resolves.toBeInTheDocument();
    expect(screen.getByText(/API version: alpha · Frontend version: frontend-test · Backend version: v-test/)).toBeInTheDocument();
    expect(fetch).toHaveBeenCalledWith(`${BACKEND_API_URL}/info`, expect.objectContaining({ method: 'GET' }));
  });

  it('allows an empty solver timeout while editing and clears its run error only after a value change', async () => {
    const user = userEvent.setup();
    const fetchMock = fetch as unknown as ReturnType<typeof vi.fn>;
    queueInitialLocalSelection(fetchMock);

    render(<OptimizeAndExportPage />);
    await screen.findByText('Server: Online');

    const timeoutInput = screen.getByRole('spinbutton');
    await user.clear(timeoutInput);
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));

    expect(screen.getByText('Solver timeout must be a valid positive integer.')).toBeInTheDocument();
    expect(timeoutInput).toHaveClass('border-red-300');
    expect(fetchMock).toHaveBeenCalledTimes(1);

    await user.type(timeoutInput, 'abc');

    expect(screen.getByText('Solver timeout must be a valid positive integer.')).toBeInTheDocument();
    expect(timeoutInput).toHaveClass('border-red-300');

    await user.type(timeoutInput, '45');

    expect(screen.queryByText('Solver timeout must be a valid positive integer.')).not.toBeInTheDocument();
    expect(timeoutInput).not.toHaveClass('border-red-300');
  });

  it('warns when frontend and backend versions differ', async () => {
    (fetch as unknown as ReturnType<typeof vi.fn>).mockResolvedValue({
      ok: true,
      json: vi.fn().mockResolvedValue({
        status: 'ready',
        api_version: 'alpha',
        app_version: 'backend-test',
      }),
    });

    render(<OptimizeAndExportPage />);

    await expect(screen.findByText(/frontend and backend versions do not match/i)).resolves.toBeInTheDocument();
  });

  it('does not warn when frontend and backend versions match', async () => {
    (fetch as unknown as ReturnType<typeof vi.fn>).mockResolvedValue({
      ok: true,
      json: vi.fn().mockResolvedValue({
        status: 'ready',
        api_version: 'alpha',
        app_version: 'frontend-test',
      }),
    });

    render(<OptimizeAndExportPage />);

    await expect(screen.findByText('Server: Online')).resolves.toBeInTheDocument();
    expect(screen.queryByText(/frontend and backend versions do not match/i)).not.toBeInTheDocument();
  });

  it('warns when frontend and backend versions match but are dirty', async () => {
    mockCurrentAppVersion.value = 'frontend-test-dirty';
    (fetch as unknown as ReturnType<typeof vi.fn>).mockResolvedValue({
      ok: true,
      json: vi.fn().mockResolvedValue({
        status: 'ready',
        api_version: 'alpha',
        app_version: 'frontend-test-dirty',
      }),
    });

    render(<OptimizeAndExportPage />);

    await expect(screen.findByText(/frontend and backend versions do not match/i)).resolves.toBeInTheDocument();
  });

  it('shows a backend check failure message when the configured backend is offline', async () => {
    (fetch as unknown as ReturnType<typeof vi.fn>).mockRejectedValue(new Error('network failed'));

    render(<OptimizeAndExportPage />);

    await expect(screen.findByText('Server: Offline')).resolves.toBeInTheDocument();
    expect(screen.getByText(/backend is not responding at the configured endpoint/i)).toBeInTheDocument();
    expect(screen.getByRole('button', { name: /optimize and download/i })).toBeDisabled();
    expect(screen.getByText(/backend unavailable/i)).toBeInTheDocument();
  });

  it('submits generic arrays and marked Exact/Range preferences through the Optimize path', async () => {
    const user = userEvent.setup();
    const preferences = [
      {
        type: 'shift count',
        person: ['P1'],
        countDates: ['01'],
        countShiftTypes: ['D'],
        expression: ['x >= T', 'x <= T'],
        target: [1, 3],
        weight: 1,
      },
      {
        type: 'shift count',
        person: ['P1'],
        countDates: ['01'],
        countShiftTypes: ['D'],
        countShiftTypeCoefficients: [['D', 16]],
        hoursContract: { unit: 'half-hour', policy: 'exact' },
        expression: 'x = T',
        target: 320,
        weight: Number.POSITIVE_INFINITY,
      },
      {
        type: 'shift count',
        person: ['P1'],
        countDates: ['01'],
        countShiftTypes: ['D'],
        countShiftTypeCoefficients: [['D', 16]],
        hoursContract: { unit: 'half-hour', policy: 'range' },
        expression: ['x >= T', 'x <= T'],
        target: [300, 340],
        weight: Number.POSITIVE_INFINITY,
      },
    ];
    mockUseSchedulingData.mockReturnValue(createSchedulingData({ preferences }));
    mockGenerateYamlFromState.mockReturnValueOnce('preferences: wire-variants\n');
    const fetchMock = queueInitialLocalSelection(fetch as unknown as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce({
        ok: false,
        status: 422,
        text: vi.fn().mockResolvedValue('submission captured'),
      });

    render(<OptimizeAndExportPage />);
    await screen.findByText('Server: Online');
    await user.click(screen.getByRole('checkbox', { name: /anonymize schedule data/i }));
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));

    await screen.findByText('Server error (422): submission captured');
    expect(mockGenerateYamlFromState.mock.lastCall?.[0].preferences).toEqual(preferences);

    const optimizeCall = fetchMock.mock.calls.find(([url]) => url === `${BACKEND_API_URL}/optimize`);
    const formData = optimizeCall?.[1]?.body as FormData;
    expect(formData.get('yaml_content')).toBe('preferences: wire-variants\n');
  });

  it('blocks normal Optimize at its named gate before sending a request', async () => {
    const user = userEvent.setup();
    mockGenerateYamlFromState.mockImplementation((_state, options) => {
      if (options?.contractedHoursBoundary === 'optimize') {
        throw new ContractedHoursBoundaryError(
          contractedHoursDiagnostic('optimize'),
        );
      }
      return 'apiVersion: alpha\n';
    });
    const fetchMock = queueInitialLocalSelection(fetch as unknown as ReturnType<typeof vi.fn>);

    render(<OptimizeAndExportPage />);
    await screen.findByText('Server: Online');
    await user.click(screen.getByRole('checkbox', { name: /anonymize schedule data/i }));
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));

    expect(screen.getByRole('alert')).toHaveTextContent("missing the explicit coefficient for 'E'");
    expect(screen.getByRole('link', { name: 'Review Contracted Hours' }))
      .toHaveAttribute('href', '/shift-counts');
    expect(fetchMock.mock.calls.filter(([url]) => url === `${BACKEND_API_URL}/optimize`))
      .toHaveLength(0);
  });

  it('keeps an existing XLSX after invalid anonymized Optimize and Download Again bypasses validation', async () => {
    const user = userEvent.setup();
    let invalid = false;
    mockGenerateYamlFromState.mockImplementation((_state, options) => {
      if (options?.contractedHoursBoundary === 'anonymized-optimize' && invalid) {
        throw new ContractedHoursBoundaryError(
          contractedHoursDiagnostic('anonymized-optimize'),
        );
      }
      return 'apiVersion: alpha\n';
    });
    queueInitialLocalSelection(fetch as unknown as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue(optimizeJobResponse({
          id: 'opt_preserved',
          state: 'completed',
          outcome: 'optimal',
          score: 1,
          solverStatus: 'OPTIMAL',
        })),
      })
      .mockResolvedValueOnce({
        ok: true,
        blob: vi.fn().mockResolvedValue(new Blob(['xlsx'])),
        headers: new Headers({ 'Content-Disposition': 'attachment; filename=preserved.xlsx' }),
      })
      .mockResolvedValueOnce({ ok: true });
    const appendChildSpy = vi.spyOn(document.body, 'appendChild');

    render(<OptimizeAndExportPage />);
    await screen.findByText('Server: Online');
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));
    await screen.findByText('Schedule optimized and downloaded successfully!');
    expect(screen.getByRole('button', { name: /download again/i })).toBeInTheDocument();

    invalid = true;
    const appendCount = appendChildSpy.mock.calls.length;
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));

    expect(screen.getByText('Contracted Hours needs attention')).toBeInTheDocument();
    const downloadAgain = screen.getByRole('button', { name: /download again/i });
    expect(downloadAgain).toBeInTheDocument();
    await user.click(downloadAgain);
    expect(appendChildSpy).toHaveBeenCalledTimes(appendCount + 1);
  });

  it('keeps a successful download when best-effort job cleanup fails', async () => {
    const user = userEvent.setup();
    const appendChildSpy = vi.spyOn(document.body, 'appendChild');
    const removeChildSpy = vi.spyOn(document.body, 'removeChild');

    queueInitialLocalSelection(fetch as unknown as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue({
          id: 'opt_test',
          state: 'queued',
          terminal: false,
          queue_position: 1,
          result: null,
          error: null,
          controls: { cancellable: true, early_completion_available: false },
          links: {
            self: '/optimize/opt_test',
            events: '/optimize/opt_test/events',
            cancellation: '/optimize/opt_test/cancel',
            early_completion: '/optimize/opt_test/finish-now',
            schedule: null,
          },
        }),
      })
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue({
          id: 'opt_test',
          state: 'completed',
          terminal: true,
          queue_position: null,
          result: {
            outcome: 'optimal',
            score: 42000,
            solver_status: 'OPTIMAL',
            termination_reason: 'optimality_proven',
          },
          error: null,
          controls: { cancellable: false, early_completion_available: false },
          links: {
            self: '/optimize/opt_test',
            events: '/optimize/opt_test/events',
            cancellation: '/optimize/opt_test/cancel',
            early_completion: '/optimize/opt_test/finish-now',
            schedule: '/optimize/opt_test/xlsx',
          },
        }),
      })
      .mockResolvedValueOnce({
        ok: true,
        blob: vi.fn().mockResolvedValue(new Blob(['xlsx'])),
        headers: new Headers({
          'Content-Disposition': 'attachment; filename=schedule.xlsx',
        }),
      })
      .mockRejectedValueOnce(new Error('cleanup failed'));

    render(<OptimizeAndExportPage />);
    await screen.findByText('Server: Online');
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));

    await expect(screen.findByText('Schedule optimized and downloaded successfully!')).resolves.toBeInTheDocument();
    expect(screen.getByText('schedule.xlsx')).toBeInTheDocument();
    expect(screen.getByText('42,000')).toBeInTheDocument();
    expect(screen.getByText('OPTIMAL')).toBeInTheDocument();

    expect(fetch).toHaveBeenCalledWith('http://localhost:8000/optimize', expect.objectContaining({ method: 'POST' }));
    expect(fetch).toHaveBeenCalledWith(
      'http://localhost:8000/optimize/opt_test',
      expect.objectContaining({ method: 'GET' })
    );
    expect(fetch).toHaveBeenCalledWith(
      'http://localhost:8000/optimize/opt_test/xlsx',
      expect.objectContaining({ method: 'GET' })
    );
    expect(fetch).toHaveBeenCalledWith(
      'http://localhost:8000/optimize/opt_test',
      expect.objectContaining({ method: 'DELETE' })
    );
    expect(appendChildSpy).toHaveBeenCalled();
    expect(removeChildSpy).toHaveBeenCalled();

    const appendCallCount = appendChildSpy.mock.calls.length;
    const removeCallCount = removeChildSpy.mock.calls.length;
    await user.click(screen.getByRole('button', { name: /download again/i }));
    expect(appendChildSpy).toHaveBeenCalledTimes(appendCallCount + 1);
    expect(removeChildSpy).toHaveBeenCalledTimes(removeCallCount + 1);
  });

  it('anonymizes schedule data by default and restores people IDs in the XLSX', async () => {
    const user = userEvent.setup();
    const xlsxBlob = new Blob(['xlsx']);
    mockUseSchedulingData.mockReturnValue(createSchedulingData({
      descriptionData: 'sensitive schedule',
      peopleData: { items: [{ id: 'Alice', description: 'sensitive person', history: [] }], groups: [], history: [] },
    }));

    queueInitialLocalSelection(fetch as unknown as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue(optimizeJobResponse({
          id: 'opt_anonymous', state: 'completed', outcome: 'optimal', score: 1, solverStatus: 'OPTIMAL',
        })),
      })
      .mockResolvedValueOnce({
        ok: true,
        blob: vi.fn().mockResolvedValue(xlsxBlob),
        headers: new Headers(),
      })
      .mockResolvedValueOnce({ ok: true });

    render(<OptimizeAndExportPage />);
    await screen.findByText('Server: Online');
    expect(screen.getByRole('checkbox', { name: /anonymize schedule data/i })).toBeChecked();
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));
    await screen.findByText('Schedule optimized and downloaded successfully!');

    const submittedState = mockGenerateYamlFromState.mock.lastCall?.[0];
    expect(submittedState).toEqual(
      expect.objectContaining({
        people: expect.objectContaining({
          items: [{ id: 'P1', history: [] }],
        }),
      })
    );
    expect(submittedState).not.toHaveProperty('description');
    expect(submittedState.people.items[0]).not.toHaveProperty('description');
    expect(mockRestorePeopleIdsInXlsx).toHaveBeenCalledWith(xlsxBlob, new Map([['P1', 'Alice']]), 1);
  });

  it('sends and downloads original people IDs when anonymization is disabled', async () => {
    const user = userEvent.setup();
    const xlsxBlob = new Blob(['xlsx']);
    mockUseSchedulingData.mockReturnValue(createSchedulingData({
      descriptionData: 'sensitive schedule',
      peopleData: { items: [{ id: 'Alice', description: 'sensitive person', history: [] }], groups: [], history: [] },
    }));

    queueInitialLocalSelection(fetch as unknown as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue(optimizeJobResponse({
          id: 'opt_named', state: 'completed', outcome: 'optimal', score: 1, solverStatus: 'OPTIMAL',
        })),
      })
      .mockResolvedValueOnce({
        ok: true,
        blob: vi.fn().mockResolvedValue(xlsxBlob),
        headers: new Headers(),
      })
      .mockResolvedValueOnce({ ok: true });

    render(<OptimizeAndExportPage />);
    await screen.findByText('Server: Online');
    await user.click(screen.getByRole('checkbox', { name: /anonymize schedule data/i }));
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));
    await screen.findByText('Schedule optimized and downloaded successfully!');

    expect(mockGenerateYamlFromState).toHaveBeenLastCalledWith(
      expect.objectContaining({
        people: expect.objectContaining({
          items: [expect.objectContaining({ id: 'Alice' })],
        }),
      }),
      { contractedHoursBoundary: 'optimize' },
    );
    expect(mockRestorePeopleIdsInXlsx).not.toHaveBeenCalled();
  });

  it('shows all received SSE event types in the optimization event log', async () => {
    const user = userEvent.setup();
    vi.stubGlobal('EventSource', MockEventSource);
    const fetchMock = fetch as unknown as ReturnType<typeof vi.fn>;

    queueInitialLocalSelection(fetchMock)
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue(optimizeJobResponse({ id: 'opt_sse' })),
      })
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue(optimizeJobResponse({
          id: 'opt_sse', state: 'completed', outcome: 'optimal', score: 42, solverStatus: 'OPTIMAL',
        })),
      })
      .mockResolvedValueOnce({
        ok: true,
        blob: vi.fn().mockResolvedValue(new Blob(['xlsx'])),
        headers: new Headers({
          'Content-Disposition': 'attachment; filename=schedule.xlsx',
        }),
      })
      .mockResolvedValueOnce({
        ok: true,
      });

    render(<OptimizeAndExportPage />);
    await screen.findByText('Server: Online');
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));
    await waitFor(() => expect(MockEventSource.instances).toHaveLength(1));

    const eventSource = MockEventSource.instances[0];
    expect(eventSource.url).toBe('http://localhost:8000/optimize/opt_sse/events');
    act(() => {
      eventSource.emit('job.state_changed', { state: 'running' });
      eventSource.emit('job.phase_changed', {
        source: 'scheduler:phase',
        code: 'creating_shift_variables',
        message: 'Creating shift variables',
        elapsedSeconds: 0.12,
      });
      eventSource.emit('job.progressed', {
        source: 'ortools/cp-sat:solution-callback',
        currentBestScore: 12000,
        elapsedSeconds: 0.1,
        solutionIndex: 2,
        commentCount: 5,
      });
    });

    expect(screen.queryByRole('img', { name: /optimization progress chart/i })).not.toBeInTheDocument();

    act(() => {
      eventSource.emit('job.progressed', {
        source: 'ortools/cp-sat:solution-callback',
        currentBestScore: 10,
        elapsedSeconds: 0.2,
        solutionIndex: 3,
        commentCount: 3,
      });
      eventSource.emit('job.state_changed', { state: 'completed' });
      eventSource.emit('job.result_available', { outcome: 'optimal', score: 42 });
    });

    await expect(screen.findByText('Schedule optimized and downloaded successfully!')).resolves.toBeInTheDocument();
    expect(screen.getAllByText('job.state_changed')).toHaveLength(2);
    expect(screen.getByText('job.phase_changed')).toBeInTheDocument();
    expect(screen.getAllByText('Creating shift variables').length).toBeGreaterThan(0);
    expect(screen.getAllByText('job.progressed')).toHaveLength(2);
    expect(screen.getByText('job.result_available')).toBeInTheDocument();
    expect(screen.getAllByText(/Comments: 5/).length).toBeGreaterThan(0);
    expect(screen.getAllByText(/Score: 12,000/).length).toBeGreaterThan(0);
    expect(screen.getByText(/"currentBestScore":12000/)).toBeInTheDocument();
    expect(screen.getByRole('img', { name: /optimization progress chart/i })).toBeInTheDocument();
    expect(eventSource.close).toHaveBeenCalledTimes(1);
    expect(fetchMock.mock.calls.filter(([url, init]) => (
      url === 'http://localhost:8000/optimize/opt_sse'
      && (init as RequestInit | undefined)?.method === 'GET'
    ))).toHaveLength(1);
  });

  it('shows queued position updates received through SSE', async () => {
    const user = userEvent.setup();
    vi.stubGlobal('EventSource', MockEventSource);

    queueInitialLocalSelection(fetch as unknown as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue(optimizeJobResponse({ id: 'opt_queued', queuePosition: 3 })),
      });

    render(<OptimizeAndExportPage />);
    await screen.findByText('Server: Online');
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));
    await waitFor(() => expect(MockEventSource.instances).toHaveLength(1));

    expect(screen.getByText('Queued, position 3')).toBeInTheDocument();
    expect(screen.getByText('Waiting in optimization queue at position 3.')).toBeInTheDocument();

    act(() => {
      MockEventSource.instances[0].emit('job.state_changed', { state: 'queued', queue_position: 2 });
    });

    expect(screen.getByText('Queued, position 2')).toBeInTheDocument();
    expect(screen.getByText('Waiting in optimization queue at position 2.')).toBeInTheDocument();

    act(() => {
      MockEventSource.instances[0].emit('job.state_changed', { state: 'running', queue_position: null });
    });

    expect(screen.getByText('running')).toBeInTheDocument();
    expect(screen.getByText('Waiting for first feasible solution...')).toBeInTheDocument();
  });

  it('does not send client heartbeats for durable jobs', async () => {
    const user = userEvent.setup();
    vi.stubGlobal('EventSource', MockEventSource);
    const setIntervalSpy = vi.spyOn(window, 'setInterval');
    const fetchMock = fetch as unknown as ReturnType<typeof vi.fn>;
    queueInitialLocalSelection(fetchMock)
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue(optimizeJobResponse({ id: 'opt_heartbeat', queuePosition: 1 })),
      })
      .mockResolvedValue({ ok: true });

    render(<OptimizeAndExportPage />);
    await screen.findByText('Server: Online');
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));
    await waitFor(() => expect(MockEventSource.instances).toHaveLength(1));

    expect(setIntervalSpy.mock.calls.some(([, delay]) => delay === 10_000)).toBe(false);
    expect(fetchMock.mock.calls.some(([url]) => String(url).includes('/heartbeat'))).toBe(false);
  });

  it('keeps a dropped SSE stream open for automatic reconnection', async () => {
    const user = userEvent.setup();
    vi.stubGlobal('EventSource', MockEventSource);
    const appendChildSpy = vi.spyOn(document.body, 'appendChild');
    const removeChildSpy = vi.spyOn(document.body, 'removeChild');

    queueInitialLocalSelection(fetch as unknown as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue(optimizeJobResponse({ id: 'opt_sse_drop' })),
      })
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue(optimizeJobResponse({
          id: 'opt_sse_drop', state: 'completed', outcome: 'optimal', score: 77, solverStatus: 'OPTIMAL',
        })),
      })
      .mockResolvedValueOnce({
        ok: true,
        blob: vi.fn().mockResolvedValue(new Blob(['xlsx'])),
        headers: new Headers({
          'Content-Disposition': 'attachment; filename=recovered.xlsx',
        }),
      })
      .mockResolvedValueOnce({
        ok: true,
      });

    render(<OptimizeAndExportPage />);
    await screen.findByText('Server: Online');
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));
    await waitFor(() => expect(MockEventSource.instances).toHaveLength(1));

    act(() => {
      MockEventSource.instances[0].listeners.get('error')?.forEach(listener => {
        listener(new Event('error') as MessageEvent);
      });
    });

    expect(screen.getByText('Optimization event stream disconnected; waiting to reconnect')).toBeInTheDocument();
    expect(MockEventSource.instances[0].close).not.toHaveBeenCalled();

    act(() => {
      MockEventSource.instances[0].emit('job.result_available', { outcome: 'optimal', score: 77 });
    });

    await expect(screen.findByText('Schedule optimized and downloaded successfully!')).resolves.toBeInTheDocument();
    expect(screen.getByText('recovered.xlsx')).toBeInTheDocument();
    expect(appendChildSpy).toHaveBeenCalled();
    expect(removeChildSpy).toHaveBeenCalled();
    expect(MockEventSource.instances[0].close).toHaveBeenCalled();
  });

  it('can request current results or cancel an active SSE job', async () => {
    const user = userEvent.setup();
    vi.stubGlobal('EventSource', MockEventSource);

    queueInitialLocalSelection(fetch as unknown as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue(optimizeJobResponse({ id: 'opt_control' })),
      })
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue(optimizeJobResponse({
          id: 'opt_control', state: 'running', earlyCompletionAvailable: false,
        })),
      })
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue(optimizeJobResponse({ id: 'opt_control', state: 'cancelling' })),
      })
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue(optimizeJobResponse({
          id: 'opt_control', state: 'cancelled', error: 'Optimization cancelled.',
        })),
      });

    render(<OptimizeAndExportPage />);
    await screen.findByText('Server: Online');
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));
    await waitFor(() => expect(MockEventSource.instances).toHaveLength(1));

    act(() => {
      MockEventSource.instances[0].emit('job.state_changed', {
        state: 'running',
        controls: { cancellable: true, early_completion_available: true },
      });
    });

    await user.click(screen.getByRole('button', { name: /get results now/i }));
    expect(fetch).toHaveBeenCalledWith(
      'http://localhost:8000/optimize/opt_control/finish-now',
      expect.objectContaining({ method: 'POST' })
    );

    await user.click(screen.getByRole('button', { name: /^cancel$/i }));
    expect(fetch).toHaveBeenCalledWith(
      'http://localhost:8000/optimize/opt_control/cancel',
      expect.objectContaining({ method: 'POST' })
    );

    act(() => {
      MockEventSource.instances[0].emit('job.state_changed', { state: 'cancelled' });
    });

    await expect(screen.findByText('Optimization cancelled.')).resolves.toBeInTheDocument();
  });

  it('keeps the optimization event log pinned to bottom when new events arrive at bottom', async () => {
    const user = userEvent.setup();
    vi.stubGlobal('EventSource', MockEventSource);

    queueInitialLocalSelection(fetch as unknown as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue(optimizeJobResponse({ id: 'opt_scroll' })),
      });

    render(<OptimizeAndExportPage />);
    await screen.findByText('Server: Online');
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));
    await waitFor(() => expect(MockEventSource.instances).toHaveLength(1));

    const eventLog = screen.getByTestId('optimization-events-log');
    Object.defineProperty(eventLog, 'clientHeight', { configurable: true, value: 100 });
    Object.defineProperty(eventLog, 'scrollHeight', { configurable: true, value: 100 });
    eventLog.scrollTop = 0;

    act(() => {
      MockEventSource.instances[0].emit('job.state_changed', { state: 'running' });
    });

    expect(eventLog.scrollTop).toBe(100);
  });

  it('does not move the optimization event log when new events arrive while scrolled up', async () => {
    const user = userEvent.setup();
    vi.stubGlobal('EventSource', MockEventSource);

    queueInitialLocalSelection(fetch as unknown as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue(optimizeJobResponse({ id: 'opt_scroll' })),
      });

    render(<OptimizeAndExportPage />);
    await screen.findByText('Server: Online');
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));
    await waitFor(() => expect(MockEventSource.instances).toHaveLength(1));

    const eventLog = screen.getByTestId('optimization-events-log');
    Object.defineProperty(eventLog, 'clientHeight', { configurable: true, value: 100 });
    Object.defineProperty(eventLog, 'scrollHeight', { configurable: true, value: 300 });
    eventLog.scrollTop = 50;

    act(() => {
      MockEventSource.instances[0].emit('job.state_changed', { state: 'running' });
    });

    expect(eventLog.scrollTop).toBe(50);
  });

  it('forbids sending and instructs users to set dates when date data is empty', async () => {
    const user = userEvent.setup();
    mockUseSchedulingData.mockReturnValue(createSchedulingData({
      dateData: { range: { startDate: undefined, endDate: undefined }, items: [], groups: [] },
    }));

    render(<OptimizeAndExportPage />);

    expect(screen.getByText(/Please set up your dates first by visiting the/i)).toBeInTheDocument();
    expect(screen.getByRole('link', { name: 'Dates' })).toHaveAttribute('href', '/dates');

    const optimizeButton = screen.getByRole('button', { name: /optimize and download/i });
    expect(optimizeButton).toBeDisabled();
    await user.click(optimizeButton);

    expect(fetch).not.toHaveBeenCalledWith('http://localhost:8000/optimize', expect.anything());
  });

  it('forbids sending and instructs users to set people when people data is empty', async () => {
    const user = userEvent.setup();
    mockUseSchedulingData.mockReturnValue(createSchedulingData({
      peopleData: { items: [], groups: [], history: [] },
    }));

    render(<OptimizeAndExportPage />);

    expect(screen.getByText(/Please set up your people first by visiting the/i)).toBeInTheDocument();
    expect(screen.getByRole('link', { name: 'People' })).toHaveAttribute('href', '/people');

    const optimizeButton = screen.getByRole('button', { name: /optimize and download/i });
    expect(optimizeButton).toBeDisabled();
    await user.click(optimizeButton);

    expect(fetch).not.toHaveBeenCalledWith('http://localhost:8000/optimize', expect.anything());
  });

  it('forbids sending and instructs users to set shift types when shift type data is empty', async () => {
    const user = userEvent.setup();
    mockUseSchedulingData.mockReturnValue(createSchedulingData({
      shiftTypeData: { items: [], groups: [] },
    }));

    render(<OptimizeAndExportPage />);

    expect(screen.getByText(/Please set up your shift types first by visiting the/i)).toBeInTheDocument();
    expect(screen.getByRole('link', { name: 'Shift Types' })).toHaveAttribute('href', '/shift-types');

    const optimizeButton = screen.getByRole('button', { name: /optimize and download/i });
    expect(optimizeButton).toBeDisabled();
    await user.click(optimizeButton);

    expect(fetch).not.toHaveBeenCalledWith('http://localhost:8000/optimize', expect.anything());
  });
});
